version: "3.0"
services:
  postgres:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_PASSWORD=aep
      - POSTGRES_USER=aep
      - POSTGRES_DB=aep
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    ports:
      - 8888:8888
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_SCHEMA=aep
      - DB_USERNAME=aep
      - DB_PASSWORD=aep
    links:
      - postgres
  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

volumes:
  postgresdb: